[build]
publish = "public"
command = "npm run build"

[[headers]]
for = "/admin/*"
[headers.values]
Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com;
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https://api.netlify.com;
      img-src 'self' data:;
      font-src 'self';
    """
